name: Manter Site Ativo

on:
  schedule:
    # Roda a cada 5 minutos
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping_site:
    runs-on: ubuntu-latest
    steps:
      - name: Ping no Render
        run: |
          curl -I -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3" https://moneylayer-2-0.onrender.com
